[project]
name = "hypodb"
version = "0.1.0"
description = "Library for connecting to Hypo MySQL databases"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.36.2",
    "pymysql>=1.1.1",
]
